{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    }
   ],
   "source": [
    "from autogen_agentchat.agents import AssistantAgent\n",
    "from autogen_core import CancellationToken\n",
    "from autogen_ext.models.openai import AzureOpenAIChatCompletionClient\n",
    "from autogen_ext.tools.graphrag import GlobalSearchTool\n",
    "from azure.identity import DefaultAzureCredential, get_bearer_token_provider"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in _map_response_single_batch\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\graphrag\\query\\structured_search\\global_search\\search.py\", line 232, in _map_response_single_batch\n",
      "    search_response = await self.llm.agenerate(\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\tools\\graphrag\\_model_adapter.py\", line 57, in agenerate\n",
      "    result: CreateResult = await self._client.create(autogen_msgs, tools=[])\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\models\\openai\\_openai_client.py\", line 497, in create\n",
      "    result: Union[ParsedChatCompletion[BaseModel], ChatCompletion] = await future\n",
      "                                                                     ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n",
      "    return await self._post(\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1843, in post\n",
      "    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1537, in request\n",
      "    return await self._request(\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1638, in _request\n",
      "    raise self._make_status_error_from_response(err.response) from None\n",
      "openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}\n",
      "Exception in _map_response_single_batch\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\graphrag\\query\\structured_search\\global_search\\search.py\", line 232, in _map_response_single_batch\n",
      "    search_response = await self.llm.agenerate(\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\tools\\graphrag\\_model_adapter.py\", line 57, in agenerate\n",
      "    result: CreateResult = await self._client.create(autogen_msgs, tools=[])\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\models\\openai\\_openai_client.py\", line 497, in create\n",
      "    result: Union[ParsedChatCompletion[BaseModel], ChatCompletion] = await future\n",
      "                                                                     ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n",
      "    return await self._post(\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1843, in post\n",
      "    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1537, in request\n",
      "    return await self._request(\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1638, in _request\n",
      "    raise self._make_status_error_from_response(err.response) from None\n",
      "openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}\n",
      "Exception in _map_response_single_batch\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\graphrag\\query\\structured_search\\global_search\\search.py\", line 232, in _map_response_single_batch\n",
      "    search_response = await self.llm.agenerate(\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\tools\\graphrag\\_model_adapter.py\", line 57, in agenerate\n",
      "    result: CreateResult = await self._client.create(autogen_msgs, tools=[])\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\models\\openai\\_openai_client.py\", line 497, in create\n",
      "    result: Union[ParsedChatCompletion[BaseModel], ChatCompletion] = await future\n",
      "                                                                     ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n",
      "    return await self._post(\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1843, in post\n",
      "    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1537, in request\n",
      "    return await self._request(\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1638, in _request\n",
      "    raise self._make_status_error_from_response(err.response) from None\n",
      "openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}\n",
      "Exception in _map_response_single_batch\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\graphrag\\query\\structured_search\\global_search\\search.py\", line 232, in _map_response_single_batch\n",
      "    search_response = await self.llm.agenerate(\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\tools\\graphrag\\_model_adapter.py\", line 57, in agenerate\n",
      "    result: CreateResult = await self._client.create(autogen_msgs, tools=[])\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\models\\openai\\_openai_client.py\", line 497, in create\n",
      "    result: Union[ParsedChatCompletion[BaseModel], ChatCompletion] = await future\n",
      "                                                                     ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n",
      "    return await self._post(\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1843, in post\n",
      "    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1537, in request\n",
      "    return await self._request(\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1638, in _request\n",
      "    raise self._make_status_error_from_response(err.response) from None\n",
      "openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}\n",
      "Exception in _map_response_single_batch\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\graphrag\\query\\structured_search\\global_search\\search.py\", line 232, in _map_response_single_batch\n",
      "    search_response = await self.llm.agenerate(\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\tools\\graphrag\\_model_adapter.py\", line 57, in agenerate\n",
      "    result: CreateResult = await self._client.create(autogen_msgs, tools=[])\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\models\\openai\\_openai_client.py\", line 497, in create\n",
      "    result: Union[ParsedChatCompletion[BaseModel], ChatCompletion] = await future\n",
      "                                                                     ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n",
      "    return await self._post(\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1843, in post\n",
      "    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1537, in request\n",
      "    return await self._request(\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1638, in _request\n",
      "    raise self._make_status_error_from_response(err.response) from None\n",
      "openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}\n",
      "Exception in _map_response_single_batch\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\graphrag\\query\\structured_search\\global_search\\search.py\", line 232, in _map_response_single_batch\n",
      "    search_response = await self.llm.agenerate(\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\tools\\graphrag\\_model_adapter.py\", line 57, in agenerate\n",
      "    result: CreateResult = await self._client.create(autogen_msgs, tools=[])\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\models\\openai\\_openai_client.py\", line 497, in create\n",
      "    result: Union[ParsedChatCompletion[BaseModel], ChatCompletion] = await future\n",
      "                                                                     ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n",
      "    return await self._post(\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1843, in post\n",
      "    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1537, in request\n",
      "    return await self._request(\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1638, in _request\n",
      "    raise self._make_status_error_from_response(err.response) from None\n",
      "openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}\n",
      "Exception in _map_response_single_batch\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\graphrag\\query\\structured_search\\global_search\\search.py\", line 232, in _map_response_single_batch\n",
      "    search_response = await self.llm.agenerate(\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\tools\\graphrag\\_model_adapter.py\", line 57, in agenerate\n",
      "    result: CreateResult = await self._client.create(autogen_msgs, tools=[])\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\models\\openai\\_openai_client.py\", line 497, in create\n",
      "    result: Union[ParsedChatCompletion[BaseModel], ChatCompletion] = await future\n",
      "                                                                     ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n",
      "    return await self._post(\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1843, in post\n",
      "    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1537, in request\n",
      "    return await self._request(\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1638, in _request\n",
      "    raise self._make_status_error_from_response(err.response) from None\n",
      "openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}\n",
      "Exception in _map_response_single_batch\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\graphrag\\query\\structured_search\\global_search\\search.py\", line 232, in _map_response_single_batch\n",
      "    search_response = await self.llm.agenerate(\n",
      "                      ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\tools\\graphrag\\_model_adapter.py\", line 57, in agenerate\n",
      "    result: CreateResult = await self._client.create(autogen_msgs, tools=[])\n",
      "                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\lpinheiro\\Github\\autogen\\python\\packages\\autogen-ext\\src\\autogen_ext\\models\\openai\\_openai_client.py\", line 497, in create\n",
      "    result: Union[ParsedChatCompletion[BaseModel], ChatCompletion] = await future\n",
      "                                                                     ^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n",
      "    return await self._post(\n",
      "           ^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1843, in post\n",
      "    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1537, in request\n",
      "    return await self._request(\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\lpinheiro\\Github\\autogen\\python\\.venv\\Lib\\site-packages\\openai\\_base_client.py\", line 1638, in _request\n",
      "    raise self._make_status_error_from_response(err.response) from None\n",
      "openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}\n",
      "Warning: All map responses have score 0 (i.e., no relevant information found from the dataset), returning a canned 'I do not know' answer. You can try enabling `allow_general_knowledge` to encourage the LLM to incorporate relevant general knowledge, at the risk of increasing hallucinations.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "I am sorry but I am unable to answer this question given the provided data.\n"
     ]
    }
   ],
   "source": [
    "openai_client = AzureOpenAIChatCompletionClient(\n",
    "    model=\"gpt-4o-mini\",\n",
    "    azure_endpoint=\"https://instinct-openai.openai.azure.com\",\n",
    "    azure_deployment=\"gpt-4o-mini\",\n",
    "    api_version=\"2024-08-01-preview\",\n",
    "    azure_ad_token=\"YOUR_AZURE_AD_TOKEN\",\n",
    "    azure_ad_token_provider=get_bearer_token_provider(\n",
    "        DefaultAzureCredential(), \"https://cognitiveservices.azure.com/.default\"\n",
    "    ),\n",
    ")\n",
    "tool = GlobalSearchTool(openai_client)\n",
    "args = {\n",
    "    \"query\": \"How does Ebenezer Scrooge’s character evolve?\",\n",
    "    \"data\": {\"input_dir\": \"C:/Users/lpinheiro/Github/autogen-test/ragtest/output\"},\n",
    "}\n",
    "result = await tool.run_json(args, CancellationToken())\n",
    "print(result)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
